tensor([[[0.4400]],
        [[0.4415]],
        [[0.4386]],
        [[0.4387]],
        [[0.4394]],
        [[0.4399]],
        [[0.4386]],
        [[0.4414]],
        [[0.4395]],
        [[0.4391]]], grad_fn=<StackBackward0>)
tensor([0, 0, 0, 0, 1, 1, 0, 1, 1, 1])
Traceback (most recent call last):
  File "/Users/dhruvachayapathy/personal/research/mit-research/plasma-data-augmentation/src/main.py", line 87, in <module>
    compute_metrics_after_training(model, test_dataset)
  File "/Users/dhruvachayapathy/personal/research/mit-research/plasma-data-augmentation/src/eval.py", line 33, in compute_metrics_after_training
    accuracy, f1, auc = compute_metrics(torch.stack(out),torch.stack(labels))
  File "/Users/dhruvachayapathy/personal/research/mit-research/plasma-data-augmentation/src/eval.py", line 10, in compute_metrics
    return accuracy_score(labels, binary_out), f1_score(labels, binary_out), roc_auc_score(labels, binary_out)
  File "/usr/local/Caskroom/miniconda/base/envs/plasma-aug/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 213, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/Caskroom/miniconda/base/envs/plasma-aug/lib/python3.10/site-packages/sklearn/metrics/_classification.py", line 213, in accuracy_score
    y_type, y_true, y_pred = _check_targets(y_true, y_pred)
  File "/usr/local/Caskroom/miniconda/base/envs/plasma-aug/lib/python3.10/site-packages/sklearn/metrics/_classification.py", line 94, in _check_targets
    raise ValueError(
ValueError: Classification metrics can't handle a mix of binary and unknown targets